services:
  flask:
    build:
      context: .
      dockerfile: ./build/flask/Dockerfile
    volumes:
      - db:/app/data
    network_mode: host

  node:
    build:
      context: .
      dockerfile: ./build/node/Dockerfile
    network_mode: host

volumes:
  db: