services:
  flask:
    build:
      context: .
      dockerfile: ./build/flask/Dockerfile
    volumes:
      - db:/app/data
    ports:
      - "5000:5000"
    network_mode: host

  node:
    build:
      context: .
      dockerfile: ./build/node/Dockerfile
    ports:
      - "3000:3000"
    network_mode: host

volumes:
  db: